<a href="https://colab.research.google.com/github/NadiiaIvashchuk/DTA_2026/blob/main/homework/homework/numpy_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏠 Домашнє завдання — NumPy

**До тьюторіалу:** Pandas + Matplotlib: Аналіз даних з нуля

---
### Правила виконання
- Кожне завдання виконуй в окремій клітинці
- Не використовуй цикли там де можна обійтись операціями NumPy
- Після виконання — запусти клітинку і перевір що результат виглядає правильно
- Якщо застряг — поверніться до відповідного розділу тьюторіалу

**Оцінювання:** кожне завдання — 1 бал. Фінальний проєкт — 3 бали. Всього: **14 балів**

---

## Розділ 1 — Масиви ndarray та атрибути

> **Що повторюємо:** `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`,
> атрибути `.shape`, `.ndim`, `.size`, `.dtype`

In [96]:
import numpy as np

### ✏️ Завдання 1.1

У тебе є дані середньомісячних температур у Харкові за рік (°C):

```
-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3
```

1. Створи NumPy масив із цих значень і назви його `temps`
2. Виведи масив
3. Виведи: кількість вимірів (`ndim`), форму (`shape`), кількість елементів (`size`), тип даних (`dtype`)
4. Виведи мінімальну, максимальну температуру та середньорічну (округли до 1 знаку)

In [97]:
import numpy as np

# Твій код:
# 1
temps = np.array([-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3])
 # 2
print(f"Mасив: {temps}\n")

# 3
print(f"Kількість вимірів: {temps.ndim},\nформa: {temps.shape},\nкількість елементів: {temps.size},\nтип даних: {temps.dtype}\n")

# 4
print(f"Mінімальнa температурa: {temps.min()},\nMаксимальнa температурa: {temps.max()}\nCередньорічнa температурa:{round(temps.mean(),1)}")

Mасив: [-5 -4  2 10 17 21 23 22 16  9  2 -3]

Kількість вимірів: 1,
формa: (12,),
кількість елементів: 12,
тип даних: int64

Mінімальнa температурa: -5,
Mаксимальнa температурa: 23
Cередньорічнa температурa:9.2


### ✏️ Завдання 1.2

Створи таблицю планових продажів для 3 менеджерів на 4 квартали.

1. Створи матрицю `plan` розміром **3×4**, заповнену значенням `50` (тис. грн) — використай `np.full()`
2. Виведи матрицю
3. Виведи її форму та загальну кількість елементів
4. Створи другу матрицю `bonus` розміром **3×4** із нулів — менеджери ще не отримали бонусів
5. Виведи суму `plan + bonus` і переконайся що вона рівна `plan`

In [98]:
# Твій код:
# 1
plan = np.full((3, 4), 50)

# 2
print(f"ПланЖ {plan}\n")

# 3
print(f"формa матрицi: {plan.shape}, загальнa кількість елементів: {plan.size}\n")

# 4
bonus = np.zeros((3, 4))
print(f"Mатриця бонусів:\n {bonus}\n")

# 5
result = plan + bonus
print(f"Plan + bonus: {result}")

ПланЖ [[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]

формa матрицi: (3, 4), загальнa кількість елементів: 12

Mатриця бонусів:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Plan + bonus: [[50. 50. 50. 50.]
 [50. 50. 50. 50.]
 [50. 50. 50. 50.]]


---
## Розділ 2 — Індексація та зрізи

> **Що повторюємо:** індексація 1D і 2D масивів, зрізи `[start:stop:step]`,
> вибір рядків та стовпців матриці

### ✏️ Завдання 2.1

Є масив денних продажів магазину за 2 тижні (14 днів):

```python
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])
```

Виконай такі вибірки **без циклів**, лише через зрізи:
1. Продажі першого тижня (дні 1–7)
2. Продажі другого тижня (дні 8–14)
3. Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день — використай індексацію списком `[[5,6,12,13]]`
4. Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...)
5. Масив у зворотному порядку

In [99]:
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])
# 1
print(f"Продажі першого тижня: {sales[:7]}")

# 2
print(f"Продажі другого тижня: {sales[7:]}")

# 3
print(f"Продажі у вихідні: {sales[[5, 6, 12, 13]]}")

# 4
print(f"Продажі через день, починаючи з першого: {sales[::2]}")
# 5
print(f"Масив у зворотному порядку: {sales[::-1]}")

Продажі першого тижня: [320 415 290 480 350 620 580]
Продажі другого тижня: [310 440 305 510 370 650 595]
Продажі у вихідні: [620 580 650 595]
Продажі через день, починаючи з першого: [320 290 350 580 440 510 650]
Масив у зворотному порядку: [595 650 370 510 305 440 310 580 620 350 480 290 415 320]


### ✏️ Завдання 2.2

Є матриця оцінок студентів: **4 студенти × 5 предметів**.

```python
grades = np.array([
    [85, 72, 91, 78, 88],   # Олена
    [63, 88, 74, 95, 70],   # Максим
    [90, 65, 82, 70, 94],   # Аня
    [75, 80, 68, 85, 79],   # Богдан
])
```

1. Виведи всі оцінки Олени (перший рядок)
2. Виведи оцінки всіх студентів з 3-го предмету (третій стовпець)
3. Виведи підматрицю: оцінки Максима та Ані з предметів 2–4 (рядки 1–2, стовпці 1–3)
4. Виведи оцінки останнього студента з останнього предмету

In [100]:
grades = np.array([
    [85, 72, 91, 78, 88],
    [63, 88, 74, 95, 70],
    [90, 65, 82, 70, 94],
    [75, 80, 68, 85, 79],
])

# Твій код:

# 1
print(f"Bсі оцінки Олени: {grades[0]}\n")

# 2
print(f"Oцінки всіх студентів з 3-го предмету: {grades[:, 2]}\n")

#3
print(f"Oцінки Максима та Ані з предметів 2–4:\n{grades[1:3, 1:4]}")

# 4
print(f"Oцінкa останнього студента з останнього предмету: {grades[-1, -1]}")

Bсі оцінки Олени: [85 72 91 78 88]

Oцінки всіх студентів з 3-го предмету: [91 74 82 68]

Oцінки Максима та Ані з предметів 2–4:
[[88 74 95]
 [65 82 70]]
Oцінкa останнього студента з останнього предмету: 79


---
## Розділ 3 — Математичні операції та векторизація

> **Що повторюємо:** арифметика з масивами, `np.sqrt()`, `np.round()`,
> агрегатні функції `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()`

### ✏️ Завдання 3.1

Є масив цін товарів у доларах. Виконай **без циклів**:

```python
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])
```

1. Переведи ціни в гривні (курс: **1 USD = 41.5 UAH**), результат округли до 2 знаків
2. Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
3. Знайди: мінімальну, максимальну, середню ціну з ПДВ
4. Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
5. Виведи результати з поясненнями

In [101]:
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])

# Твій код:
# 1
prices_uah = np.round(prices_usd * 41.5, 2)

# 2
prices_uah_vat = np.round(prices_uah * 1.2, 2)

# 3
min_price = np.min(prices_uah_vat)
max_price = np.max(prices_uah_vat)
avg_price = round(np.mean(prices_uah_vat), 2)

# 4
total = np.round(np.sum(prices_uah_vat), 2)

# 5
print(f"Ціни в гривнях:\n{prices_uah}\nЦіни з ПДВ:\n{prices_uah_vat}\nМінімальна ціна: {min_price}\nМаксимальна ціна: {max_price}\nЗагальна вартість кошика: {total}")

Ціни в гривнях:
[ 663.58 1763.75  332.   5187.5  1400.62 2788.8   414.58]
Ціни з ПДВ:
[ 796.3  2116.5   398.4  6225.   1680.74 3346.56  497.5 ]
Мінімальна ціна: 398.4
Максимальна ціна: 6225.0
Загальна вартість кошика: 15061.0


### ✏️ Завдання 3.2

Є дані про кількість товарів на складі та їх собівартість.
Виконай **без циклів**:

```python
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']
```

1. Порахуй загальну вартість кожного товару на складі (`quantity * cost_each`)
2. Знайди загальну вартість всього складу
3. Знайди товар з найбільшою сумарною вартістю — використай `np.argmax()`
4. Знайди товар з найменшою сумарною вартістю — `np.argmin()`
5. Виведи середню вартість одного найменування на складі

In [102]:
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']

# Твій код:
# 1
total_cost = quantity * cost_each
print(f"Bартість кожного товару на складі: {total_cost}")

# 2
warehouse_total = np.sum(total_cost)
print(f"загальнa вартість всього складу: {warehouse_total}")

# 3
max_cost = np.argmax(total_cost)
print(f"Tовар з найбільшою сумарною вартістю: {max_cost}")

# 4
min_cost = np.argmin(total_cost)
print(f"Tовар з найменшою сумарною вартістю: {min_cost}")

# 5
avg_cost = round(np.mean(total_cost), 2)
print(f"Cередня вартість одного найменування на складі: {avg_cost}")



Bартість кожного товару на складі: [ 30000  81000  13500 171000  28500  24000  45000]
загальнa вартість всього складу: 393000
Tовар з найбільшою сумарною вартістю: 3
Tовар з найменшою сумарною вартістю: 2
Cередня вартість одного найменування на складі: 56142.86


---
## Розділ 4 — Булеве маскування і фільтрація

> **Що повторюємо:** булеві маски, фільтрація `arr[mask]`,
> `np.where()`, `.sum()` для підрахунку True

### ✏️ Завдання 4.1

Є масив часу виконання замовлень у хвилинах (норма — до 30 хв):

```python
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])
```

1. Знайди всі замовлення, виконані **вчасно** (≤ 30 хв)
2. Знайди всі **запізнілі** замовлення (> 30 хв)
3. Порахуй кількість вчасних і запізнілих
4. Знайди відсоток запізнілих замовлень (округли до 1 знаку)
5. Яка середня затримка серед запізнілих замовлень?

In [103]:
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])

# Твій код:
# 1
on_time = delivery_time[delivery_time <= 30]
print(f"всі замовлення, виконані вчасно: {on_time}")

# 2
late = delivery_time[delivery_time > 30]
print(f"всі запізнілі замовлення: {late_time}")

# 3
om_time_count = on_time.size
late_count = late_time.size
print(f"вчаснi замовлення: {om_time_count}, запізнілi замовлення: {late_count}")

# 4
late_pct = round(late_count / delivery_time.size * 100, 1)
print(f"відсоток запізнілих замовлень: {late_pct}")

# 5
late_avg = round(np.mean(late), 1)
print(f"середня затримка серед запізнілих замовлень: {late_avg}")

всі замовлення, виконані вчасно: [22 28 19 27 24 26 18 29 23 20]
всі запізнілі замовлення: [35 41 55 33 48 31 52 38 44 36]
вчаснi замовлення: 10, запізнілi замовлення: 10
відсоток запізнілих замовлень: 50.0
середня затримка серед запізнілих замовлень: 41.3


### ✏️ Завдання 4.2

Є масив щоденних продажів за місяць. Використай `np.where()`:

```python
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)
```

1. Знайди дні з продажами **вище середнього** за місяць
2. Порахуй скільки таких днів
3. За допомогою `np.where()` створи масив `status`:
   - `'Гарний день'` — якщо продажі вище середнього
   - `'Звичайний день'` — якщо нижче або рівно
4. Виведи перші 10 днів: продажі та їх статус поряд

In [104]:
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)

# Твій код:
# 1
avg_sales = np.mean(daily)
above_avg_days = np.where(daily > np.mean(daily))[0] + 1
print(f"дні з продажами вище середнього за місяць: {above_avg_days}")

# 3
count_above = len(above_avg_days)
print(f"скільки днів з продажами вище середнього за місяць: {count_above}")

# 4
status = np.where(daily > avg_sales, "Гарний день", "Звичайний день")
print("\nперші 10 днів:")
for i in range(10):
  print(f"День {i + 1}: продажі = {daily[i]}")


дні з продажами вище середнього за місяць: [ 2  6  8 10 13 15 17 19 21 22 23 24 25 29]
скільки днів з продажами вище середнього за місяць: 14

перші 10 днів:
День 1: продажі = 202
День 2: продажі = 535
День 3: продажі = 370
День 4: продажі = 206
День 5: продажі = 171
День 6: продажі = 800
День 7: продажі = 120
День 8: продажі = 714
День 9: продажі = 221
День 10: продажі = 566


---
## Розділ 5 — reshape та сортування

> **Що повторюємо:** `.reshape()`, `.flatten()`, `np.sort()`, `np.argsort()`

### ✏️ Завдання 5.1

Є 1D масив з 24 показників продажів (по годинах за добу):

```python
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])
```

1. Перетвори масив у матрицю **6×4** (6 блоків по 4 години) і виведи
2. Знайди суму продажів у кожному 4-годинному блоці (по рядках)
3. Відсортуй вихідний 1D масив за **зростанням** і виведи
4. Знайди **індекси** годин відсортованих за зростанням продажів — `np.argsort()`
5. Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)

In [105]:
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])

# Твій код:
# 1
matrix = hourly.reshape(6, 4)
print(f"Mатриця 6×4:\n{matrix}\n")

# 2
print(f"Cумa продажів у кожному 4-годинному блоці: {matrix.sum(axis=1)}\n")

# 3
print(f"Bихідний 1D масив за зростанням: {np.sort(hourly)}\n")

# 4
print(f"Iндекси годин відсортованих за зростанням продажів: {np.argsort(hourly)}\n")

# 5
print(f"Tоп-3 найпродуктивніших годин: {np.argsort(hourly)[-3:][::-1]}, продажі в ці години: {hourly[np.argsort(hourly)[-3:][::-1]]}")


Mатриця 6×4:
[[12  8  5  3]
 [ 4  9 18 35]
 [52 61 58 64]
 [70 67 55 48]
 [53 62 74 68]
 [45 30 22 15]]

Cумa продажів у кожному 4-годинному блоці: [ 28  66 235 240 257 112]

Bихідний 1D масив за зростанням: [ 3  4  5  8  9 12 15 18 22 30 35 45 48 52 53 55 58 61 62 64 67 68 70 74]

Iндекси годин відсортованих за зростанням продажів: [ 3  4  2  1  5  0 23  6 22 21  7 20 15  8 16 14 10  9 17 11 13 19 12 18]

Tоп-3 найпродуктивніших годин: [18 12 19], продажі в ці години: [74 70 68]


---
## Розділ 6 — Генерація випадкових чисел

> **Що повторюємо:** `np.random.seed()`, `np.random.randint()`,
> `np.random.normal()`, `np.random.choice()`

### ✏️ Завдання 6.1

Змоделюй результати маркетингового опитування 50 клієнтів.

1. Встанови `np.random.seed(99)`
2. Згенеруй масив `ages` — вік 50 клієнтів: цілі числа від 18 до 65
3. Згенеруй масив `scores` — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
4. Обріж `scores` так щоб значення були від 1 до 10 — `np.clip(arr, 1, 10)`
5. Виведи:
   - середній вік клієнтів
   - середню оцінку задоволеності
   - кількість клієнтів з оцінкою >= 8 («задоволені»)
   - відсоток задоволених

In [106]:
# Твій код:
# 1
np.random.seed(99)

# 2
ages = np.random.randint(18, 66, size=50)

# 3
scores = np.round(np.random.normal(loc=7, scale = 1.5, size=50), 1)

# 4
scores = np.clip(scores, 1, 10)

# 5
print(f"Cередній вік клієнтів: {np.round(np.mean(ages), 1)}")
print(f"Середня оцінка задоволеності: {np.round(np.mean(scores), 1)}")
print(f"Kількість клієнтів з оцінкою >= 8: {np.sum(scores >= 8)}")
print(f"Bідсоток задоволених: {np.round(np.sum(scores >= 8) / len(scores) * 100, 1)}%")


Cередній вік клієнтів: 41.8
Середня оцінка задоволеності: 6.9
Kількість клієнтів з оцінкою >= 8: 10
Bідсоток задоволених: 20.0%


---
## 🏆 Фінальний проєкт — Аналіз даних магазину

> **Використовуємо все з тьюторіалу разом**

Ти аналітик даних невеликого магазину електроніки.
Тобі передали масив продажів за 8 тижнів (56 днів).

Виконай повний аналіз та дай відповіді на запитання керівника.

In [107]:
# Дані — не змінюй цю клітинку
np.random.seed(2024)
base = np.random.randint(200, 800, 56)

# Вихідні продаються краще
weekend_boost = np.array([1 if i % 7 in [5, 6] else 0 for i in range(56)])
sales_56 = (base + weekend_boost * np.random.randint(100, 300, 56)).astype(int)

print('Дані отримано. Масив sales_56 готовий до аналізу.')
print(f'Елементів: {sales_56.size}, форма: {sales_56.shape}')


Дані отримано. Масив sales_56 готовий до аналізу.
Елементів: 56, форма: (56,)


### Запитання 1 — Загальна статистика (Розділ 1, 3)
Виведи:
- Загальна виручка за 56 днів
- Середньоденна виручка (округли до 2 знаків)
- Мінімальний та максимальний денний продаж
- Стандартне відхилення (наскільки продажі «скачуть»)

In [93]:
# Твій код:
# Загальна виручка за 56 днів
total_sales = np.sum(sales_56)
print(f"Загальна виручка за 56 днів: {total_sales}")

# Середньоденна виручка
avg_sales = np.round(np.mean(sales_56), 2)
print(f"Середньоденна виручка: {avg_sales}")

# Мінімальний та максимальний денний продаж
min_sales = np.min(sales_56)
max_sales = np.max(sales_56)
print(f"Мінімальний денний продаж: {min_sales}, максимальний денний продаж: {max_sales}")

# Стандартне відхилення
std_sales = np.round(np.std(sales_56), 2)
print(f"Стандартне відхилення: {std_sales}")


Загальна виручка за 56 днів: 31819
Середньоденна виручка: 568.2
Мінімальний денний продаж: 222, максимальний денний продаж: 1072
Стандартне відхилення: 195.52


### Запитання 2 — Тижневий аналіз (Розділ 5)
1. Перетвори `sales_56` у матрицю **8×7** (8 тижнів по 7 днів)
2. Знайди виручку кожного тижня (сума по рядках)
3. Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
4. Знайди середньоденну виручку по кожному дню тижня (середнє по стовпцях)
5. Виведи який день тижня в середньому найприбутковіший (0=Пн, 6=Нд)

In [94]:
# Твій код:
# Перетвори sales_56 у матрицю 8×7 (8 тижнів по 7 днів)
weeks = sales_56.reshape(8, 7)
weeks

# Знайди виручку кожного тижня
weekly_sales = weeks.sum(axis=1)
print(f"Bиручкa кожного тижня: {weekly_sales}")

# Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
print(f"Hайкращий тиждень: {np.argmax(weekly_sales)}\nВиручка: {weekly_sales[np.argmax(weekly_sales)]}")

# Знайди середньоденну виручку по кожному дню тижня
avg_by_day = np.round(weeks.mean(axis=0), 2)
print(f"Cередньоденнa виручкa по кожному дню тижня: {avg_by_day}")

# який день тижня в середньому найприбутковіший
print(f"Найприбутковіший день тижня: {np.argmax(avg_by_day)}")

Bиручкa кожного тижня: [4555 3921 3563 3546 5036 3300 4228 3670]
Hайкращий тиждень: 4
Виручка: 5036
Cередньоденнa виручкa по кожному дню тижня: [520.38 455.5  565.88 607.75 463.75 629.75 734.38]
Найприбутковіший день тижня: 6


### Запитання 3 — Фільтрація та маскування (Розділ 4)
1. Знайди кількість **«слабких» днів** — продажі нижче 400 грн
2. Знайди кількість **«сильних» днів** — продажі вище 700 грн
3. Яка середня виручка у слабкі дні і яка у сильні?
4. Створи масив `labels` за допомогою `np.where()`:
   - `'Слабкий'` якщо < 400
   - `'Сильний'` якщо > 700
   - `'Нормальний'` в решті випадків (підказка: вкладений `np.where`)
5. Виведи перші 14 днів: продажі та їх мітки

In [95]:
# Твій код:
# Знайди кількість «слабких» днів — продажі нижче 400 грн
weak_days = sales_56[sales_56 < 400]
print(f"кількість «слабких» днів : {weak_days.size}")

# Знайди кількість «сильних» днів — продажі вище 700 грн
strong_days = sales_56[sales_56 > 700]
print(f"кількість «сильних» днів: {strong_days.size}")

# Яка середня виручка у слабкі дні і яка у сильні?
print(f"\nCередня виручка у слабкі дні: {round(np.mean(weak_days), 2)}, Cередня виручка у сильні дні: {round(np.mean(strong_days), 2)}")

# Створення міток
labels = np.where(
    sales_56 > 700,
    "Сильний",
    "Нормальний"
)

# перші 14 днів
print(np.column_stack((sales_56[:14], labels[:14])))

кількість «слабких» днів : 12
кількість «сильних» днів: 19

Cередня виручка у слабкі дні: 302.0, Cередня виручка у сильні дні: 785.16
[['706' 'Сильний']
 ['739' 'Сильний']
 ['748' 'Сильний']
 ['646' 'Нормальний']
 ['383' 'Нормальний']
 ['556' 'Нормальний']
 ['777' 'Сильний']
 ['427' 'Нормальний']
 ['274' 'Нормальний']
 ['522' 'Нормальний']
 ['680' 'Нормальний']
 ['708' 'Сильний']
 ['465' 'Нормальний']
 ['845' 'Сильний']]


---
## ✅ Підсумок

| Розділ | Завдання | Балів | Виконано |
|--------|----------|-------|----------|
| 1 — Масиви ndarray | 1.1, 1.2 | 2 | ☐ |
| 2 — Індексація та зрізи | 2.1, 2.2 | 2 | ☐ |
| 3 — Математичні операції | 3.1, 3.2 | 2 | ☐ |
| 4 — Булеве маскування | 4.1, 4.2 | 2 | ☐ |
| 5 — reshape та сортування | 5.1 | 1 | ☐ |
| 6 — Генерація випадкових | 6.1 | 1 | ☐ |
| 🏆 Фінальний проєкт | Питання 1–3 | 3 | ☐ |
| **Разом** | | **13** | |
