<a href="https://colab.research.google.com/github/NadiiaIvashchuk/DTA_2026/blob/main/classmade/python_numpy_practice_no_answers_ua.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐍 Практика: Python + NumPy для аналітика даних

Цей блокнот — чиста практика. Мінімум теорії, максимум задач.

---
### Як працювати
- **Shift+Enter** — запустити клітинку
- Спочатку спробуй сам, потім порівняй з розв'язком у блокноті з відповідями
- Навіть неправильна спроба вчить більше ніж підгляд
---

---
# Частина 1 — Основний синтаксис Python

## Блок 1.1 — Змінні та типи даних

### 📋 Задача 1
Є дані одного продажу. Створи змінні та виведи підсумок у такому форматі:
```
Товар:     Ноутбук
Ціна:      34500 грн
Знижка:    10%
До сплати: 31050.0 грн
```

In [4]:
product  = 'Ноутбук'
price    = 34500
discount = 10   # відсотків

# Порахуй суму до сплати та виведи результат
print(f"Товар: {product} \n"
      f"Ціна: {price} грн.\n"
      f"Знижка: {discount} % \n"
      f"До сплати: {round(price - (price * discount/100),2)} грн.")


Товар: Ноутбук 
Ціна: 34500 грн.
Знижка: 10 % 
До сплати: 31050.0 грн.


### 📋 Задача 2
Визнач тип кожної змінної та виведи його.
Потім перетвори рядок `'2024'` на ціле число та додай 1.

In [94]:
a = 42
b = 3.14
c = 'аналітик'
d = True
e = '2024'

# Виведи тип кожної змінної — hint: type()
# Перетвори e на int та додай 1
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(int(e) + 1)

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'str'>
2025


---
## Блок 1.2 — Рядки та форматування

### 📋 Задача 3
Маємо сирий рядок із назвою міста та пробілами. Зроби:
1. Прибери зайві пробіли по краях — `.strip()`
2. Зроби першу літеру великою — `.title()`
3. Виведи кількість символів в очищеній назві
4. Перевір чи починається рядок з літери `'К'`

In [54]:
city = '   харків   '

print(city.strip())
print(city.strip().title())
print(len(city.strip()))
city == "K"
city.startswith("K")

харків
Харків
6


False

### 📋 Задача 4
Є рядок з даними у форматі CSV (через кому).
Розбий його на окремі значення і виведи кожне з його номером.
```
0: Олена
1: Маркетинг
2: 32000
...
```

In [60]:
row = 'Олена,Маркетинг,32000,Київ,5'

# Розбий рядок на список — hint: .split(',')
# Виведи кожне значення з індексом — hint: enumerate()

list_name = (row.split(","))

for el, i in enumerate(list_name):
    print(el, ":", i)

0 : Олена
1 : Маркетинг
2 : 32000
3 : Київ
4 : 5


---
## Блок 1.3 — Списки

### 📋 Задача 5
Маємо список оцінок студента. Виконай дії:
1. Додай оцінку `91` в кінець — `.append()`
2. Видали `47` (помилка введення) — `.remove()`
3. Відсортуй за спаданням — `.sort(reverse=True)`
4. Виведи найвищу та найнижчу оцінку

In [75]:
grades = [85, 47, 92, 78, 88, 74, 95, 61]
grades.append(91)
print(grades)
grades.pop(1)
print(grades)
grades.sort(reverse=True)
sorted(grades)
print(grades)
print(min(grades))
print(max(grades))

[85, 47, 92, 78, 88, 74, 95, 61, 91]
[85, 92, 78, 88, 74, 95, 61, 91]
[95, 92, 91, 88, 85, 78, 74, 61]
61
95


### 📋 Задача 6
Є список чисел. За допомогою **зрізів** виконай без циклів:
1. Перші 3 елементи
2. Останні 3 елементи
3. Кожен другий елемент
4. Список у зворотному порядку

In [102]:
numbers = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
print(numbers[:3])
print(numbers[-3:])
print(numbers[1::2])
print(numbers[::-1])
numbers[numbers.index(20)] = -20
print(numbers)
numbers[1:2] = [4,5,6]
print(numbers)

[10, 20, 30]
[80, 90, 100]
[20, 40, 60, 80, 100]
[100, 90, 80, 70, 60, 50, 40, 30, 20, 10]
[10, -20, 30, 40, 50, 60, 70, 80, 90, 100]
[10, 4, 5, 6, 30, 40, 50, 60, 70, 80, 90, 100]


### 📋 Задача 7 — List comprehension
Перепиши кожну операцію **одним рядком** за допомогою list comprehension:
`[вираз for елемент in список]`

In [116]:
prices = [100, 250, 80, 420, 175, 310]

# 1. Список цін з ПДВ (×1.2) — одним рядком
prices_vat = [el * 1.2 for el in prices]
print(prices_vat)

# 2. Тільки ціни більше 200 — одним рядком
big_prices = [price for price in prices if price > 200]
print(big_prices)

# 3. Рядки виду 'Ціна: 100 грн' для кожної ціни — одним рядком
labels = [f'Ціна: {price} грн' for price in prices]
print(labels)

[120.0, 300.0, 96.0, 504.0, 210.0, 372.0]
[250, 420, 310]
['Ціна: 100 грн', 'Ціна: 250 грн', 'Ціна: 80 грн', 'Ціна: 420 грн', 'Ціна: 175 грн', 'Ціна: 310 грн']


---
## Блок 1.4 — Словники

### 📋 Задача 8
Є словник із даними співробітника. Виконай:
1. Додай ключ `'досвід'` зі значенням `5`
2. Збільш зарплату на 10%
3. Виведи всі ключі, значення та пари `key: value`
4. Перевір чи є ключ `'відділ'`

In [134]:
employee = {
    "ім'я":    'Максим',
    'відділ':  'IT',
    'зарплата': 65000,
    'місто':   'Харків'
}
employee.update({'досвід':5})
employee['зарплата'] *= 1.10
find_key = employee.get('відділ')
print(employee)
print(find_key)
for key, value in employee.items():
  #print(key)
  #print(value)
  print(key, value)

#'відділ' in employee

if 'відділ' in employee:
  print(True)
else:
  print(False)

{"ім'я": 'Максим', 'відділ': 'IT', 'зарплата': 71500.0, 'місто': 'Харків', 'досвід': 5}
IT
ім'я Максим
відділ IT
зарплата 71500.0
місто Харків
досвід 5
True


### 📋 Задача 9
Є список рядків-записів. Перетвори їх у список словників:
```python
[{'місто': 'Київ', 'продажі': 145000, 'місяць': 'Січень'}, ...]
```
Підказка: `split(',')` та `int()`

In [137]:
raw_data = [
    'Київ,145000,Січень',
    'Харків,98000,Січень',
    'Одеса,76000,Січень',
    'Львів,112000,Січень',
]

records = []
# Твій код — заповни records
for item in raw_data:
  city, salary, month = item.split(",")
  record = {
      "city": city,
      "salary": int(salary),
      "month": month
      }
  records.append(record)
print(records)

[{'city': 'Київ', 'salary': '145000', 'month': 'Січень'}, {'city': 'Харків', 'salary': '98000', 'month': 'Січень'}, {'city': 'Одеса', 'salary': '76000', 'month': 'Січень'}, {'city': 'Львів', 'salary': '112000', 'month': 'Січень'}]


---
## Блок 1.5 — Умови та цикли

### 📋 Задача 10
Напиши функцію `classify_sale(amount)`, яка повертає:
- `'Мале'` — менше 500 грн
- `'Середнє'` — від 500 до 2000 грн включно
- `'Велике'` — більше 2000 грн

Протестуй на значеннях: `150, 750, 500, 2000, 5500`

In [141]:
def classify_sale(amount):
    if amount < 500:
      return "Мале"
    elif amount > 2000:
      return "Велике"
    else:
      return "Середнє"
test_values = [150, 750, 500, 2000, 5500]
for val in test_values:
    print(f'{val:>6} грн → {classify_sale(val)}')


   150 грн → Мале
   750 грн → Середнє
   500 грн → Середнє
  2000 грн → Середнє
  5500 грн → Велике


### 📋 Задача 11
Є список чисел із «брудними» значеннями (від'ємні — помилки, нулі — відсутні дані).

Напиши цикл `for`, який:
1. Пропускає від'ємні числа — `continue`
2. Зупиняється на нулі — `break`
3. Рахує суму та кількість валідних значень
4. Виводить середнє

In [150]:
measurements = [23, 45, -5, 67, 12, -3, 89, 0, 44, 56]

total = 0
count = 0

for val in measurements:
    if val == 0:
      break
    elif val < 0:
      continue
    else:
      total = total + val
      count = count + 1
print(total, count)
print(f"середнє: {total / count}")


236 5
середнє: 47.2


---
## Блок 1.6 — Функції

### 📋 Задача 12
Напиши функцію `summary(data)`, яка приймає список чисел і повертає **словник**:
`{'min': ..., 'max': ..., 'sum': ..., 'mean': ..., 'count': ...}`

Використовуй лише вбудовані функції: `min()`, `max()`, `sum()`, `len()`

In [156]:
def summary(data):
   num_dict = {
       'min': min(data),
       'max': max(data),
       'sum': sum(data),
       'mean': sum(data) / len(data),
       'count': len(data)
   }
   return num_dict

sales = [4500, 8200, 3100, 9700, 5600, 2300, 7800]
result = summary(sales)

for key, val in result.items():
    print(f'{key:>6}: {val}')


   min: 2300
   max: 9700
   sum: 41200
  mean: 5885.714285714285
 count: 7


### 📋 Задача 13
Напиши функцію `filter_records(records, field, value)`, яка повертає
список словників де `record[field] == value`.

Протестуй: знайди всіх з IT та всіх з Києва.

In [159]:
employees = [
    {"ім'я": 'Олена', 'відділ': 'IT',        'місто': 'Київ'},
    {"ім'я": 'Максим', 'відділ': 'Маркетинг', 'місто': 'Харків'},
    {"ім'я": 'Аня',    'відділ': 'IT',        'місто': 'Київ'},
    {"ім'я": 'Богдан', 'відділ': 'HR',        'місто': 'Львів'},
    {"ім'я": 'Катя',   'відділ': 'IT',        'місто': 'Одеса'},
]

def filter_records(records, field, value):
    list = []
    for record in records:
      if record[field] == value:
        list.append(record)
    return list

it_team = filter_records(employees, 'відділ', 'IT')
print(f'IT: {len(it_team)} осіб')

kyiv = filter_records(employees, 'місто', 'Київ')
print(f'Київ: {len(kyiv)} осіб')


IT: 3 осіб
Київ: 2 осіб


---
# Частина 2 — NumPy: масиви та операції

In [160]:
import numpy as np
print('NumPy:', np.__version__, '✅')

NumPy: 2.0.2 ✅


---
## Блок 2.1 — Створення масивів

### 📋 Задача 14
Створи масиви різними способами і виведи для кожного: вміст, `dtype` та `shape`.

In [182]:
# 1. Масив із списку: [5, 10, 15, 20, 25]
arr_1 = np.array([5, 10, 15, 20, 25])
print(f"{arr_1} \n {arr_1.dtype} \n {arr_1.shape}")
# 2. Масив нулів розміром 4×3
zeros = np.zeros((4, 3))
print(f"{zeros} \n {zeros.dtype} \n {zeros.shape}")
# 3. Масив одиниць розміром 2×5
ones = np.ones((2, 5))
print(f"{ones} \n {ones.dtype} \n {ones.shape}")
# 4. Числа від 1 до 20 з кроком 3   — hint: np.arange
arr_2 = np.arange(1, 21, 3)
print(f"{arr_2} \n {arr_2.dtype} \n {arr_2.shape}")
# 5. 6 рівномірних чисел від 0 до 1 — hint: np.linspace
even_num = np.linspace(0, 1, 6)
print(f"{even_num} \n {even_num.dtype} \n {even_num.shape}")

[ 5 10 15 20 25] 
 int64 
 (5,)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 float64 
 (4, 3)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
 float64 
 (2, 5)
[ 1  4  7 10 13 16 19] 
 int64 
 (7,)
[0.  0.2 0.4 0.6 0.8 1. ] 
 float64 
 (6,)


### 📋 Задача 15
Створи матрицю 3×3 із числами від 1 до 9, потім:
1. Виведи форму та кількість елементів
2. Змін форму на 9×1
3. Змін форму на 1×9
4. Розгорни у плоский масив — `flatten()`

In [199]:
# Hint: np.arange(1, 10).reshape(3, 3)
arr_3 = np.arange(1, 10).reshape(3, 3)
print(f"{arr_3} \n {arr_3.shape}")
arr_4 = arr_3.reshape(9, 1)
print(f"{arr_4} \n {arr_4.shape}")
arr_5 = arr_4.reshape(1, 9)
print(f"{arr_5} \n {arr_5.shape}")
arr_6 = arr_5.flatten()
print(f"{arr_6} \n {arr_6.shape}")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 (3, 3)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 
 (9, 1)
[[1 2 3 4 5 6 7 8 9]] 
 (1, 9)
[1 2 3 4 5 6 7 8 9] 
 (9,)


### 📋 Задача 14+ (додаткова)
Створи такі спеціальні масиви та виведи кожен:
1. Одиничну матрицю 4×4 — `np.eye()`
2. Масив із 5 випадкових цілих чисел від 1 до 100 — `np.random.randint()`
3. Масив із 4 випадкових чисел нормального розподілу (μ=0, σ=1) — `np.random.randn()`
4. Масив, заповнений числом `7`, розміром 3×3 — `np.full()`

In [240]:
np.random.seed(42)   # фіксує випадковість — результат завжди однаковий
ones = np.eye(4, 4)
print(ones)
rnd_arr = np.random.randint(1, 101, 5)
print(rnd_arr)
normal = np.random.randn(4)
print(normal)
sevens = np.full((3, 3), 7)
print(sevens)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[52 93 15 72 61]
[-1.19780643  2.14165843 -0.094621   -0.9288281 ]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


---
## Блок 2.2 — Індексація та зрізи

### 📋 Задача 16
Є масив продажів за 10 днів. Виконай вибірку **без циклів** через зрізи:
1. Перші 3 дні
2. Останні 3 дні
3. Кожен другий день
4. Дні з 3-го по 7-й включно
5. Масив у зворотному порядку

In [211]:
daily_sales = np.array([320, 410, 285, 590, 340, 615, 280, 475, 390, 510])
print(f"Перші 3 дні: {daily_sales[:3]}") #1
print(f"Останні 3 дні: {daily_sales[-3:]}") #2
print(f"Кожен другий день: {daily_sales[1::2]}") #3
print(f"Дні з 3-го по 7-й включно: {daily_sales[2:7]}") #4
print(f"Масив у зворотному порядку: {daily_sales[::-1]}") #5

Перші 3 дні: [320 410 285]
Останні 3 дні: [475 390 510]
Кожен другий день: [410 590 615 475 510]
Дні з 3-го по 7-й включно: [285 590 340 615 280]
Масив у зворотному порядку: [510 390 475 280 615 340 590 285 410 320]


### 📋 Задача 17
Є матриця 4×4 — продажі по магазинах (рядки) і тижнях (стовпці). Виконай вибірку:
1. Весь перший рядок (магазин 1)
2. Весь другий стовпець (тиждень 2)
3. Підматриця: магазини 2–3, тижні 2–3
4. Останній рядок і останній стовпець

In [224]:
sales = np.array([
    [150, 210, 180, 240],   # Магазин 1
    [120, 190, 210, 175],   # Магазин 2
    [200, 165, 195, 220],   # Магазин 3
    [135, 145, 160, 195],   # Магазин 4
])
print(f"Магазин 1: {sales[0, :]}")
print(f"тиждень 2: {sales[:, 1]}")
print(f"Підматриця: {sales[1:3, 1:3]}")
print(f"Останній рядок і останній стовпець: {sales[-1], sales[:, -1]}")

Магазин 1: [150 210 180 240]
тиждень 2: [210 190 165 145]
Підматриця: [[190 210]
 [165 195]]
Останній рядок і останній стовпець: (array([135, 145, 160, 195]), array([240, 175, 220, 195]))


### 📋 Задача 16+ (додаткова)
Є масив з 10 елементів. Виконай:
1. Виведи елементи з парними індексами (0, 2, 4...)
2. Виведи три середніх елементи (індекси 3, 4, 5)
3. Змін значення останніх двох елементів на `0`
4. Виведи масив після зміни

In [249]:
arr = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99, 100])
print(f"Виведи елементи з парними індексами: {arr[::2]}")
print(f"Виведи три середніх елементи: {arr[3:6]}")
arr[-2:] = 0
print(arr)

Виведи елементи з парними індексами: [11 33 55 77 99]
Виведи три середніх елементи: [44 55 66]
[11 22 33 44 55 66 77 88  0  0]


---
## Блок 2.3 — Математичні операції та векторизація

### 📋 Задача 18
Є масив цін у доларах. Виконай **без циклів**:
1. Переведи в гривні (курс 41)
2. Додай ПДВ 20%
3. Заокругли до цілих
4. Знайди мінімум, максимум, суму, середнє

In [262]:
prices_usd = np.array([12.5, 34.0, 8.75, 59.99, 23.0, 41.5])
prices_uah = prices_usd * 41
print(prices_uah)

print(f"Salary&VAT: {np.round(prices_uah * 1.2)}")
print(f"мінімум: {prices_uah.min()}")
print(f"максимум: {prices_uah.max()}")
print(f"сумa: {prices_uah.sum()}")
print(f"середнє: {prices_uah.mean()}")

[ 512.5  1394.    358.75 2459.59  943.   1701.5 ]
Salary&VAT: [ 615. 1673.  430. 2952. 1132. 2042.]
мінімум: 358.75
максимум: 2459.59
сумa: 7369.34
середнє: 1228.2233333333334


### 📋 Задача 19
Є два масиви — кількість і ціна за одиницю. Знайди:
1. Виручку по кожному товару (поелементне множення)
2. Загальну виручку
3. Середню ціну товарів
4. Товар з максимальною виручкою — `np.argmax()`

In [269]:
quantities = np.array([30, 12, 85, 7,  42, 19])
unit_price = np.array([500, 2400, 120, 8500, 350, 1200])
names      = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор', 'Мишка', 'Навушники']

revenue = quantities * unit_price
print(f"Виручкa по кожному товару: {revenue}")
total_revenue = revenue.sum()
print(f"Загальнa виручкa: {total_revenue}")
print(f"Товар з максимальною виручкою: {names[np.argmax(revenue)]}")

Виручкa по кожному товару: [15000 28800 10200 59500 14700 22800]
Загальнa виручкa: 151000
Товар з максимальною виручкою: Монітор


### 📋 Задача 18+ (додаткова)
Є масив балів тесту (0–100). Знайди **без циклів**:
1. Кількість студентів, що склали тест (бал >= 60)
2. Кількість студентів, що не склали
3. Відсоток тих, хто склав
4. Середній бал серед тих, хто склав

In [279]:
scores = np.array([72, 45, 88, 91, 55, 63, 78, 34, 82, 67,
                   59, 94, 41, 76, 85, 52, 69, 38, 73, 90])
passed = scores >= 60
print(f"Кількість студентів, що склали тест: {passed.sum()}")
print(f"Кількість студентів, що не склали: {np.sum(~passed)}")
print(f"Відсоток тих, хто склав: {passed.sum() / len(scores) * 100}%")
print(f"Середній бал серед тих, хто склав: {np.mean(scores[passed])}")

Кількість студентів, що склали тест: 13
Кількість студентів, що не склали: 7
Відсоток тих, хто склав: 65.0%
Середній бал серед тих, хто склав: 79.07692307692308


---
## Блок 2.4 — Булева індексація та фільтрація

### 📋 Задача 20
Є масив температур за місяць. Знайди:
1. Дні з температурою вище 25°C
2. Кількість таких днів
3. Середня температура в «спекотні» (>25°C) і «прохолодні» (≤25°C) дні
4. Заміни всі від'ємні значення нулем

In [287]:
temps = np.array([22, 28, 31, 19, 25, 34, 27, 18, -2, 23,
                  29, 33, 21, 26, 30, 17, 24, 32, 28, 20,
                  -1, 25, 31, 29, 23, 27, 35, 22, 19, 26])
high_temps = temps >= 25

print(f"Дні з температурою вище 25°C: {high_temps}")
print(f"Кількість днів з температурою вище 25°C: {high_temps.sum()}")
print(f"Середня температура в «спекотні» (>25°C): {np.mean(temps[high_temps])} і «прохолодні» (≤25°C) дні: {np.mean(temps[temps <= 25])}")
temps[temps < 0] = 0
print(temps)

Дні з температурою вище 25°C: [False  True  True False  True  True  True False False False  True  True
 False  True  True False False  True  True False False  True  True  True
 False  True  True False False  True]
Кількість днів з температурою вище 25°C: 17
Середня температура в «спекотні» (>25°C): 29.176470588235293 і «прохолодні» (≤25°C) дні: 18.333333333333332
[22 28 31 19 25 34 27 18  0 23 29 33 21 26 30 17 24 32 28 20  0 25 31 29
 23 27 35 22 19 26]


### 📋 Задача 21
Є дані про замовлення: масив сум та масив статусів. Виконай аналіз:
1. Сума всіх завершених замовлень (`'done'`)
2. Кількість `'pending'`
3. Середня сума скасованих (`'cancelled'`)
4. Завершені замовлення з сумою > 1000 грн

In [297]:
np.random.seed(42)
amounts  = np.random.randint(200, 5000, 20)
statuses = np.random.choice(['done', 'pending', 'cancelled'], 20,
                             p=[0.6, 0.25, 0.15])

print('Суми:    ', amounts)
print('Статуси: ', statuses)

finished_orders = (amounts > 1000) & (statuses == 'done')

print(f"Сума всіх завершених замовлень: {np.sum(amounts[statuses == 'done'])}")
print(f"Кількість 'pending': {np.sum(statuses == 'pending')}")
print(f"Завершені замовлення з сумою > 1000 грн: {finished_orders}")

Суми:     [1060 3972 3292  666 4626 3644 3371 3119  330 1885  969 2591 2633 1384
 4755 3585 4317 3104  674 1282]
Статуси:  ['done' 'done' 'cancelled' 'done' 'done' 'pending' 'done' 'cancelled'
 'done' 'cancelled' 'pending' 'done' 'done' 'cancelled' 'done' 'done'
 'done' 'done' 'done' 'pending']
Сума всіх завершених замовлень: 35684
Кількість 'pending': 3
Завершені замовлення з сумою > 1000 грн: [ True  True False False  True False  True False False False False  True
  True False  True  True  True  True False False]


### 📋 Задача 20+ (додаткова)
Є масив зарплат співробітників. Виконай:
1. Знайди тих, чия зарплата вище середньої
2. Знайди тих, чия зарплата нижче 30000 грн
3. Заміни всі зарплати нижче 25000 значенням 25000 (мінімальна ставка)
4. Виведи масив до і після зміни

In [308]:
salaries = np.array([45000, 28000, 72000, 19000, 38000,
                     55000, 23000, 61000, 34000, 82000])
above_avg_salary = salaries > np.mean(salaries)

print(f"чия зарплата вище середньої: {above_avg_salary}")
print(f"зарплата нижче 30000 грн: {salaries[salaries < 30000]}")
print(salaries)
salaries[salaries < 25000] = 25000
print(salaries)


чия зарплата вище середньої: [False False  True False False  True False  True False  True]
зарплата нижче 30000 грн: [28000 19000 23000]
[45000 28000 72000 19000 38000 55000 23000 61000 34000 82000]
[45000 28000 72000 25000 38000 55000 25000 61000 34000 82000]


---
## Блок 2.5 — Агрегація по матрицях

### 📋 Задача 22
Є матриця продажів: 4 менеджери × 6 місяців. Знайди **без циклів**:
1. Загальні продажі кожного менеджера (сума по рядках, `axis=1`)
2. Загальні продажі кожного місяця (сума по стовпцях, `axis=0`)
3. Найкращий менеджер — `argmax()`
4. Найкращий місяць
5. Середнє по всій матриці

In [ ]:
sales = np.array([
    [45, 52, 48, 61, 55, 70],   # Менеджер 1
    [38, 44, 60, 55, 68, 72],   # Менеджер 2
    [62, 58, 51, 67, 73, 65],   # Менеджер 3
    [41, 49, 54, 47, 59, 63],   # Менеджер 4
])  # одиниці — тисячі грн

managers = ['Олена', 'Максим', 'Аня', 'Богдан']
months   = ['Січ', 'Лют', 'Бер', 'Кві', 'Тра', 'Чер']


### 📋 Задача 22+ (додаткова)
Є матриця оцінок: 3 студенти × 4 предмети. Знайди:
1. Середній бал кожного студента (по рядках)
2. Середній бал по кожному предмету (по стовпцях)
3. Максимальний бал у кожного студента
4. Студент з найвищим середнім балом

In [ ]:
grades = np.array([
    [85, 72, 91, 78],   # Студент 1
    [63, 88, 74, 95],   # Студент 2
    [90, 65, 82, 70],   # Студент 3
])

students = ['Олена', 'Максим', 'Аня']
subjects = ['Математика', 'Програмування', 'Статистика', 'Англійська']


---
## Блок 2.6 — Комплексні задачі

### 📋 Задача 23 — Нормалізація даних
Нормалізація (Min-Max scaling) — важлива техніка в ML.
Формула: `x_norm = (x - min) / (max - min)`
Результат завжди від 0 до 1.

Напиши функцію `normalize(arr)` і застосуй до масиву.

In [ ]:
def normalize(arr):
    pass

scores = np.array([45, 72, 88, 34, 91, 60, 77, 55, 83, 49])
normalized = normalize(scores)

print('Оригінал:    ', scores)
print('Нормалізовано:', normalized)
# Мін має бути 0, макс — 1


### 📋 Задача 24 — Виявлення викидів
Викид — значення далі ніж **2 стандартних відхилення** від середнього.

Умова викиду: `|x - mean| > 2 * std`

Знайди та виведи викиди та їх індекси.

In [ ]:
data = np.array([23, 25, 22, 24, 26, 150, 23, 25, 22, 24,
                 21, 27, 23, 25, -80, 24, 26, 23, 25, 22])

# 1. Порахуй mean та std
# 2. Знайди маску викидів — hint: np.abs()
# 3. Виведи самі викиди та їх індекси — hint: np.where()


### 📋 Задача 25 — Фінальна комплексна
Є дані про 5 магазинів за 12 місяців.

Знайди **без циклів**:
1. Загальну річну виручку кожного магазину
2. Кращий місяць для кожного магазину (`argmax` по рядках)
3. Кількість місяців де виручка магазину була вище його власного середнього
4. Відсоток таких місяців від загальної кількості

In [ ]:
np.random.seed(7)
revenue = np.random.randint(50, 200, size=(5, 12))
stores  = ['Магазин A', 'Магазин B', 'Магазин C', 'Магазин D', 'Магазин E']
months  = ['Січ','Лют','Бер','Кві','Тра','Чер','Лип','Сер','Вер','Жов','Лис','Гру']

print('Дані (тис. грн):')
print(revenue)


---
## 📋 Ключові прийоми аналітика

### Python — базовий синтаксис

```python
# ── Типи та конвертація ──────────────────────────────────
type(x)            # дізнатись тип змінної
int('42')          # рядок → ціле число
float('3.14')      # рядок → дійсне число
str(100)           # число → рядок
bool(0)            # будь-що → булеве

# ── Рядки ────────────────────────────────────────────────
s.strip()          # прибрати пробіли по краях
s.split(',')       # розбити на список по розділювачу
s.replace('a','b') # замінити підрядок
s.lower()          # всі малі літери
s.upper()          # всі великі літери
s.title()          # Перша Велика В Кожному Слові
s.startswith('К')  # чи починається з ...
f'{val:.2f}'       # форматування числа (2 знаки після коми)
f'{val:>8}'        # вирівняти праворуч на 8 символів

# ── Списки ───────────────────────────────────────────────
lst.append(x)      # додати в кінець
lst.remove(x)      # видалити перше входження x
lst.sort()         # сортувати на місці (змінює список)
sorted(lst)        # повернути новий відсортований список
lst[a:b]           # зріз від a до b (b не включається)
lst[::2]           # кожен другий елемент
lst[::-1]          # реверс списку
len(lst)           # кількість елементів

# List comprehension — одним рядком:
[x*2 for x in lst]              # застосувати до всіх
[x for x in lst if x > 0]       # відфільтрувати
[f'{x} грн' for x in lst]       # перетворити на рядки

# ── Словники ─────────────────────────────────────────────
d['key']           # отримати значення
d['key'] = val     # додати або оновити
d.keys()           # всі ключі
d.values()         # всі значення
d.items()          # пари (ключ, значення)
'key' in d         # чи є ключ у словнику

# ── Цикли та умови ───────────────────────────────────────
for i, val in enumerate(lst):   # індекс + значення
for a, b in zip(lst1, lst2):    # пари з двох списків
continue                         # перейти до наступної ітерації
break                            # вийти з циклу

# ── Функції ──────────────────────────────────────────────
min(lst), max(lst), sum(lst), len(lst)   # вбудовані агрегати
round(x, 2)                              # округлення
abs(x)                                   # модуль числа
```

---

### NumPy — масиви та операції

```python
import numpy as np

# ── Створення масивів ────────────────────────────────────
np.array([1, 2, 3])          # зі списку
np.zeros((3, 4))             # нулі розміром 3×4
np.ones((2, 5))              # одиниці розміром 2×5
np.full((3, 3), 7)           # заповнити числом 7
np.eye(4)                    # одинична матриця 4×4
np.arange(0, 10, 2)          # [0, 2, 4, 6, 8]
np.linspace(0, 1, 5)         # 5 рівних точок від 0 до 1
np.random.randint(1, 100, 10) # 10 випадкових цілих 1–99
np.random.randn(5)            # 5 чисел нормального розподілу

# ── Форма та інформація ──────────────────────────────────
arr.shape     # розміри: (рядки, стовпці)
arr.ndim      # кількість вимірів
arr.size      # загальна кількість елементів
arr.dtype     # тип даних (int64, float64...)
arr.reshape(3, 4)   # нова форма (кількість елементів та сама)
arr.flatten()       # розгорнути у 1D

# ── Індексація та зрізи ──────────────────────────────────
arr[0]          # перший елемент (1D)
arr[-1]         # останній
arr[2:5]        # елементи з індексу 2 по 4
arr[::2]        # кожен другий
arr[::-1]       # зворотній порядок

# Для 2D матриці:
m[0, :]         # весь перший рядок
m[:, 1]         # весь другий стовпець
m[1:3, 1:3]     # підматриця рядки 1–2, стовпці 1–2
m[-1, :]        # останній рядок
m[:, -1]        # останній стовпець

# ── Математичні операції (без циклів!) ───────────────────
arr * 2            # помножити всі елементи на 2
arr + 10           # додати до всіх
arr1 * arr2        # поелементне множення двох масивів
np.sqrt(arr)       # квадратний корінь
np.abs(arr)        # абсолютне значення
np.round(arr, 2)   # округлення

# ── Агрегатні функції ────────────────────────────────────
arr.sum()          # сума всіх
arr.mean()         # середнє
arr.std()          # стандартне відхилення
arr.min()          # мінімум
arr.max()          # максимум
np.median(arr)     # медіана

# Для матриць — по осях:
m.sum(axis=0)      # сума по стовпцях ↓ (результат — рядок)
m.sum(axis=1)      # сума по рядках → (результат — стовпець)
m.mean(axis=1, keepdims=True)  # зберегти форму для broadcast

# ── Знайти позицію ───────────────────────────────────────
np.argmin(arr)     # індекс мінімального елемента
np.argmax(arr)     # індекс максимального елемента
np.where(умова)    # індекси де умова True

# ── Булева індексація (фільтрація) ───────────────────────
arr[arr > 5]             # лише елементи > 5
arr[arr < 0] = 0         # замінити від'ємні нулем
mask = arr > 5
arr[mask]                # застосувати маску
arr[~mask]               # інвертована маска (НЕ)

# Кілька умов:
arr[(arr > 5) & (arr < 20)]   # І
arr[(arr < 0) | (arr > 100)]  # АБО

# ── Корисні прийоми ──────────────────────────────────────
mask.sum()               # кількість True (скільки відповідає умові)
mask.mean() * 100        # відсоток True

arr.copy()               # копія (зміни не вплинуть на оригінал)

# Нормалізація Min-Max:
(arr - arr.min()) / (arr.max() - arr.min())

# Виявлення викидів (правило 2σ):
np.abs(arr - arr.mean()) > 2 * arr.std()

# Z-score (стандартизація):
(arr - arr.mean()) / arr.std()
```

In [93]:
a = [12,13,14,55]
d = "sdfggh"
list(zip(a, d, strict=False))
a.extend([None] * (len(d) - len(a))) #add a value
list(zip(a, d))

[(12, 's'), (13, 'd'), (14, 'f'), (55, 'g'), (None, 'g'), (None, 'h')]